apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress
      interval: 1m
  targetNamespace: ingress
  values:
    controller.service.annotations.service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    controller.service.annotations.service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
    controller.replicaCount: 2
