apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-alb
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: oci://mcr.microsoft.com/application-lb/charts/alb-controller
      interval: 5m
  targetNamespace: azure-alb-system
  values:
    albController:
      podIdentity:
        clientID:
          secretRef:
            name: cluster-configuration-protected-parameters
            key: albidentityclientid
