apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 5m
      values:
        controller:
          service:
            annotations.service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            annotations.service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
          replicaCount: 2
  targetNamespace: ingress-system
