apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: alb-controller
  namespace: flux-system
spec:
  interval: 2m
  prune: true
  wait: true
  sourceRef:
    kind: OCIRepository
    name: alb-controller
  targetNamespace: azure-alb-system
values:
  albController:
    podIdentity:
      clientID:
        secretRef:
          name: cluster-configuration-protected-parameters
          key: albidentityclientid
