---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-resource-quota
  namespace: testdeveloper
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 4Gi
    limits.cpu: "15"
    limits.memory: 8Gi
    pods: "50"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: testdeveloper
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx:1.7.9
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 750m
              memory: 256Mi
      nodeSelector:
        "kubernetes.io/os": linux
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: testdeveloper
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: myapp-pdb
  namespace: testdeveloper
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: myapp
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
  namespace: testdeveloper
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  targetCPUUtilizationPercentage: 3 # target CPU utilization
